_G.json = require("libs.json.json")

function Initialise()
    -- Resolution of the screen in a vector
    _G.RES = vector.new(love.graphics.getWidth(),love.graphics.getHeight()) 

    -- Setting up other fonts to be used
    _G.BOLD_FONT = love.graphics.newFont("assets/font/Fredoka/static/Fredoka_SemiExpanded-SemiBold.ttf", 48)
    UpdateButtonPositions()

    -- Loading textures
    _G.textures = {}
    local buttons = {}
    local enemies = {}
    local blades = {}
    local score_displays = {}

    buttons.up = love.graphics.newImage("assets/textures/buttons/up_button.png")
    buttons.down = love.graphics.newImage("assets/textures/buttons/down_button.png")
    buttons.left = love.graphics.newImage("assets/textures/buttons/left_button.png")
    buttons.right = love.graphics.newImage("assets/textures/buttons/right_button.png")

    enemies.up = love.graphics.newImage("assets/textures/enemies/up_enemy.png")
    enemies.down = love.graphics.newImage("assets/textures/enemies/down_enemy.png")
    enemies.left = love.graphics.newImage("assets/textures/enemies/left_enemy.png")
    enemies.right = love.graphics.newImage("assets/textures/enemies/right_enemy.png")

    score_displays.good = love.graphics.newImage("assets/textures/UI/good.png")
    score_displays.great = love.graphics.newImage("assets/textures/UI/great.png")
    score_displays.perfect = love.graphics.newImage("assets/textures/UI/perfect.png")
    score_displays.amazing = love.graphics.newImage("assets/textures/UI/amazing.png")
    score_displays.x2 = love.graphics.newImage("assets/textures/UI/x2.png")
    score_displays.x3 = love.graphics.newImage("assets/textures/UI/x3.png")
    score_displays.x4 = love.graphics.newImage("assets/textures/UI/x4.png")
    score_displays.x5 = love.graphics.newImage("assets/textures/UI/x5.png")


    textures.buttons = buttons
    textures.enemies = enemies
    textures.score_displays = score_displays

    -- Get list of songs available
    _G.song_list = {}
    UpdateSongList()

    -- Setup scene
    _G.menu = ReturnMenu()

    -- Setup keys pressed since last frame table
    _G.key_presses_frame = {}
end


function LoadLevel(level_path)
    local csv = require("libs.csv.lua.csv")
    local level = csv.open("level_path")
end

function _G.UpdateSongList()
    _G.song_list = {}
    local iterator = 1
    local f = io.open("add_songs_here.txt")
    if f ~= nil then
        io.close(f)
        for line in io.lines("add_songs_here.txt") do
            table.insert(song_list, iterator, {})
            song_list[iterator].folder_path = ("assets/songs/" .. line)
            song_list[iterator].folder_name = line
            local song_info, _ = loadJSONData((song_list[iterator].folder_path).."/info.json")
            song_list[iterator].song_info = song_info
            local song_data, _ = loadJSONData((song_list[iterator].folder_path).."/level.json")
            song_list[iterator].song_data = song_data
            iterator = iterator + 1
        end
    else
        table.insert(song_list, 1, {})
        song_list[1].folder_path = ("assets/songs/Alright")
        song_list[1].folder_name = ("Alright")
        local song_info, err = loadJSONData((song_list[1].folder_path).."/info.json")
        print(err)
        song_list[1].song_info = song_info
        local song_data, err = loadJSONData((song_list[1].folder_path).."/level.json")
        print(err)
        song_list[1].song_data = song_data

        table.insert(song_list, 2, {})
        song_list[2].folder_path = ("assets/songs/Gorgeous")
        song_list[2].folder_name = ("Gorgeous")
        local song_info, err = loadJSONData((song_list[2].folder_path).."/info.json")
        print(err)
        song_list[2].song_info = song_info
        local song_data, err = loadJSONData((song_list[2].folder_path).."/level.json")
        print(err)
        song_list[2].song_data = song_data
    end

end

function LoadGame(song_path)
    _G.game = ReturnGame(song_path)
end


-- Generated by Google Gemini --

--- Loads and parses a JSON file into a Lua table.

function _G.loadJSONData(filename)
    -- 1. Open the file
    local file, err_open = love.filesystem.read(filename)
    if not file then
        return nil, "Error opening file: " .. (err_open or "unknown error")
    end

    -- 3. Decode the JSON string
    -- We use pcall (protected call) to safely catch any errors during parsing
    -- This API (json_lib.decode) is compatible with rxi/json.lua
    local ok, data_or_err = pcall(json.decode, file)
    if not ok then
        return nil, "JSON decode error: " .. tostring(data_or_err)
    end

    -- 4. Return the successfully parsed table
    return data_or_err
end


-- --- Example Usage ---
-- (You would typically 'require' this file in your main game script)
--
-- local loadJSONData = require("level_loader")
-- local levelData, err = loadJSONData("level.json")
--
-- if err then
--     print("Failed to load level data:")
--     print(err)
-- else
--     print("Level data loaded successfully!")
--
--     -- Example: Accessing a value
--     -- Note: JSON keys are strings, so "10.5" is accessed with brackets.
--     local enemy1_dmg = levelData["10.log.json:5"]["enm"]["1"]["dmg"]
--     print("Timestamp 10.5, Enemy 1 Damage: " .. enemy1_dmg)
-- end


-- Return the function so other scripts can 'require' this file
return loadJSONData

-- End of Google Gemini generation --